spring.application.name=job4j_cars

app.hibernate.config=hibernate.cfg.xml

spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/job4j_cars
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=password

spring.liquibase.change-log=classpath:db/dbchangelog.xml

spring.thymeleaf.cache=false
